package:
  name: oors
  version: {{ environ.get("GIT_DESCRIBE_TAG", "")[1:] }}

source:
  git_url: ..

build:
  noarch: python
  number: {{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}
  string: py_{{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}+git{{ environ.get("GIT_FULL_HASH", "")[:8] }}
  entry_points:
    - aqctl_oors = oors.aqctl_oors:main
  script: $PYTHON setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python >=3.5.3
    - setuptools
  run:
    - python >=3.5.3
#    - artiq

test:
  imports:
    - oors.tcp
#     - oors.aqctl_oors

about:
  home: https://github.com/quartiq/oors
  license: LGPL
  summary: 'Driver for opticlock ORS'
